title: Skinny Banner
context:
    headline: We've made changes to our Clubcard Reward Partners
    subhead: View our FAQs to find out more
    img: https://secure.tesco.com/clubcard/boost/CMSAssets/UK/rewards/default/img/placeholder-images/ddl/483x110.jpg




